### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by Igro182** [google-developer-training/basic-android-kotlin-compose-training-unscramble#9]
It seems to be an error on Step 8 Update Score and Count 

There is a check done in here: 
`fun checkUserGuess() {
   if (_uiState.value.userGuess.equals(currentWord, true)) {
       // User's guess is correct, increase the score
       val updatedScore = _uiState.value.score.plus(SCORE_INCREASE)
   } else {
       //...
   }
}`

However on this step properties of uiState are: 
`data class GameUiState(
   val currentScrambledWord: String = "",
   val isGuessedWordWrong: Boolean = false,
   val score: Int = 0
)`

There is no property called userGuess

is it an error or read something wrong?

**Comment by git-jr** [comment]
Seems an error, the correct code in this step is:

`    fun checkUserGuess() {
        if (userGuess.equals(currentWord,true)) {
            val updateScore = _uiState.value.score.plus(SCORE_INCREASE)...}`

**Comment by tugceaktepe** [comment]
step [6.5 ](https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#5) said that : 

_In the GameViewModel.kt file, add a var property called userGuess. Use mutableStateOf() so that Compose observes this value and sets the initial value to ""_ 

```
var userGuess by mutableStateOf("")
   private set
```

**Comment by osuleymanova** [comment]
Hello @Igro182,

Thanks for reaching out to us and sharing your concern. The typo in the code snippet is fixed:

![Screen Shot 2022-12-14 at 2 58 38 PM](https://user-images.githubusercontent.com/86437155/207733724-80cf7105-de50-44d5-a95c-3f76fc9aeb40.png)
